In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from fanalysis.ca import CA
from matplotlib.ticker import PercentFormatter

from scipy.stats import chi2_contingency  
from scipy.stats import chi2

data = pd.read_csv('data.csv')

## Chi2 d'indépendance : famille de situation en fonction du parcours de stage. 

### Pour SN1 et Urgences

In [2]:
data_FS = pd.pivot_table(data=data, values="record_id", columns="order_1", index="FS", aggfunc="count")
display(data_FS)

order_1,SN1 avant Urgences,Urgences avant SN1
FS,,
FS01,22,23
FS02,30,22
FS03,7,14
FS04,9,14
FS05,5,12
FS06,2,6
FS07,3,4
FS08,18,21
FS09,14,12


In [3]:
chi_squared_result=chi2_contingency(data_FS)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  8.823648076439454 
La p-valeur du test est :  0.5489179432480569 
Nombre de degré de liberté :  10 

Le quantile de la loi du chi 2 à 10 degré de liberté associé au niveau de confiance 0.05 est 18.307038053275146 

Valeurs attendues : 
 [[20.86206897 24.13793103]
 [24.10727969 27.89272031]
 [ 9.73563218 11.26436782]
 [10.66283525 12.33716475]
 [ 7.88122605  9.11877395]
 [ 3.70881226  4.29118774]
 [ 3.24521073  3.75478927]
 [18.08045977 20.91954023]
 [12.05363985 13.94636015]
 [ 6.02681992  6.97318008]
 [ 4.63601533  5.36398467]]


**Conclusion** : La p-value est très supérieure à 0.05 on ne peut pas rejeter l'hypothèse nulle. Il ne semble pas y avoir de corrélation entre le parcours de stage et les familles de situation abordées.  
A noter que certaines valeurs observées et attendues sont inférieures à 5 donc les conditions de validité du test ne sont théoriquement pas vérifiées. 

### Pour SN2 et pôle femme

In [11]:
data_FS = pd.pivot_table(data=data, values="record_id", columns="order_2", index="FS", aggfunc="count")
display(data_FS)

order_2,Pôle femme avant SN2,SN2 avant Pôle femme
FS,,
FS01,NaN,45.0
FS02,NaN,52.0
FS03,1.0,20.0
FS04,NaN,23.0
FS05,NaN,17.0
FS06,NaN,8.0
FS07,NaN,7.0
FS08,NaN,39.0
FS09,NaN,26.0


Pour le moment ces analyses ne sont pas pertinentes puisque les SN2 de notre base de données sont tous passés en SN2 d'abord. 

### Pour la pédiatrie ambulatoire

In [14]:
data_FS = pd.pivot_table(data=data, values="record_id", columns="ped_ambu", index="FS", aggfunc="count", fill_value=0)
display(data_FS)

ped_ambu,non,oui
FS,,
FS01,32,13
FS02,34,18
FS03,12,9
FS04,18,5
FS05,14,3
FS06,8,0
FS07,5,2
FS08,30,9
FS09,22,4


In [15]:
chi_squared_result=chi2_contingency(data_FS)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  12.882056497620862 
La p-valeur du test est :  0.23034115166689356 
Nombre de degré de liberté :  10 

Le quantile de la loi du chi 2 à 10 degré de liberté associé au niveau de confiance 0.05 est 18.307038053275146 

Valeurs attendues : 
 [[33.10344828 11.89655172]
 [38.25287356 13.74712644]
 [15.44827586  5.55172414]
 [16.91954023  6.08045977]
 [12.50574713  4.49425287]
 [ 5.88505747  2.11494253]
 [ 5.14942529  1.85057471]
 [28.68965517 10.31034483]
 [19.12643678  6.87356322]
 [ 9.56321839  3.43678161]
 [ 7.35632184  2.64367816]]


**Conclusion** : la p-value est supérieure à 0.5 donc on n'observe pas de différence significative dans la répartition des familles de situation associée à la réalisation du stage de pédiatrie en ambulatoire. 

## Chi2 d'indépendance : problématiques exemplaire en fonction du parcours de stage. 

### Pour SN1 et Urgences 

In [4]:
data_PE = pd.pivot_table(data=data, values="record_id", columns="order_1", index="PE", aggfunc="count")
display(data_PE)

order_1,SN1 avant Urgences,Urgences avant SN1
PE,,
PE01,17,23
PE02,18,18
PE03,6,7
PE04,11,12
PE05,15,18
PE06,12,13
PE07,6,6
PE08,5,18
PE09,9,14


In [5]:
chi_squared_result=chi2_contingency(data_PE)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  12.11564167892833 
La p-valeur du test est :  0.20686823032354565 
Nombre de degré de liberté :  9 

Le quantile de la loi du chi 2 à 9 degré de liberté associé au niveau de confiance 0.05 est 16.918977604620448 

Valeurs attendues : 
 [[18.5440613  21.4559387 ]
 [16.68965517 19.31034483]
 [ 6.02681992  6.97318008]
 [10.66283525 12.33716475]
 [15.29885057 17.70114943]
 [11.59003831 13.40996169]
 [ 5.56321839  6.43678161]
 [10.66283525 12.33716475]
 [10.66283525 12.33716475]
 [15.29885057 17.70114943]]


**Conclusion** : La p-value est très supérieure à 0.05 on ne peut pas rejeter l'hypothèse nulle. Il ne semble pas y avoir de corrélation entre le parcours de stage et les problématiques exemplaires abordées. 

### Pour la pédiatrie ambulatoire

In [16]:
data_PE = pd.pivot_table(data=data, values="record_id", columns="ped_ambu", index="PE", aggfunc="count", fill_value=0)
display(data_PE)

ped_ambu,non,oui
PE,,
PE01,32,8
PE02,26,10
PE03,12,1
PE04,19,4
PE05,24,9
PE06,14,11
PE07,10,2
PE08,18,5
PE09,18,5


In [17]:
chi_squared_result=chi2_contingency(data_PE)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  13.627076883419038 
La p-valeur du test est :  0.13622291343649642 
Nombre de degré de liberté :  9 

Le quantile de la loi du chi 2 à 9 degré de liberté associé au niveau de confiance 0.05 est 16.918977604620448 

Valeurs attendues : 
 [[29.42528736 10.57471264]
 [26.48275862  9.51724138]
 [ 9.56321839  3.43678161]
 [16.91954023  6.08045977]
 [24.27586207  8.72413793]
 [18.3908046   6.6091954 ]
 [ 8.82758621  3.17241379]
 [16.91954023  6.08045977]
 [16.91954023  6.08045977]
 [24.27586207  8.72413793]]


**Conclusion** : La p-value est très supérieure à 0.05 on ne peut pas rejeter l'hypothèse nulle. Il ne semble pas y avoir de corrélation entre la réalisation du stage de pédiatrie en ambulatoire et les problématiques exemplaires abordées. 

## Chi2 d'indépendance : résultats de consultation en fonction du parcours de stage. 

### Pour SN1 et Urgences

In [6]:
data_RC = pd.pivot_table(data=data, values="record_id", columns="order_1", index="RC", aggfunc="count")
display(data_RC.head)

<bound method NDFrame.head of order_1                       SN1 avant Urgences  Urgences avant SN1
RC                                                                  
?                                            1.0                 NaN
ACCIDENT VASCULAIRE CÉRÉBRAL                 NaN                 1.0
ACNÉ VULGAIRE                                NaN                 2.0
ADÉNOPATHIE                                  1.0                 NaN
ALCOOL (PROBLÈME AVEC L’)                    1.0                 NaN
...                                          ...                 ...
VULVITE - VAGINITE                           1.0                 1.0
ZONA                                         NaN                 2.0
ÉNURÉSIE PSYCHOGÈNE                          NaN                 1.0
ÉPISTAXIS                                    NaN                 1.0
ÉRYSIPÈLE                                    1.0                 NaN

[85 rows x 2 columns]>

**Note** : On observe de nombreuses valeurs nulles et quasiment toute les valeurs sont < 5. Le test du Chi2 ne serait donc pas pertinent dans cette situation. 

### Pour la pédiatrie ambulatoire

In [18]:
data_RC = pd.pivot_table(data=data, values="record_id", columns="ped_ambu", index="RC", aggfunc="count")
display(data_RC.head)

<bound method NDFrame.head of ped_ambu                      non  oui
RC                                    
?                             1.0  NaN
ACCIDENT VASCULAIRE CÉRÉBRAL  NaN  1.0
ACNÉ VULGAIRE                 2.0  NaN
ADÉNOPATHIE                   1.0  NaN
ALCOOL (PROBLÈME AVEC L’)     1.0  NaN
...                           ...  ...
VULVITE - VAGINITE            2.0  NaN
ZONA                          1.0  1.0
ÉNURÉSIE PSYCHOGÈNE           1.0  NaN
ÉPISTAXIS                     1.0  NaN
ÉRYSIPÈLE                     1.0  NaN

[85 rows x 2 columns]>

## Chi2 d'indépendance : item en fonction du parcours de stage. 

### Pour SN1 et Urgences

In [7]:
data_item = pd.pivot_table(data=data, values="record_id", columns="order_1", index="ecn_item", aggfunc="count")
display(data_item.head)

<bound method NDFrame.head of order_1   SN1 avant Urgences  Urgences avant SN1
ecn_item                                        
Item 1                  19.0                20.0
Item 103                 2.0                 1.0
Item 105                 NaN                 1.0
Item 11                  NaN                 1.0
Item 110                 1.0                 3.0
...                      ...                 ...
Item 87                  NaN                 1.0
Item 94                  2.0                 2.0
Item 95                  NaN                 1.0
Item 96                  NaN                 1.0
Item 99                  NaN                 1.0

[98 rows x 2 columns]>

**Note** : On observe de nombreuses valeurs nulles et quasiment toute les valeurs sont < 5. Le test du Chi2 ne serait donc pas pertinent dans cette situation. 

### Pour la pédiatrie ambulatoire

In [19]:
data_item = pd.pivot_table(data=data, values="record_id", columns="ped_ambu", index="ecn_item", aggfunc="count")
display(data_item.head)

<bound method NDFrame.head of ped_ambu   non  oui
ecn_item           
Item 1    31.0  8.0
Item 103   3.0  NaN
Item 105   1.0  NaN
Item 11    1.0  NaN
Item 110   3.0  1.0
...        ...  ...
Item 87    1.0  NaN
Item 94    1.0  3.0
Item 95    1.0  NaN
Item 96    1.0  NaN
Item 99    1.0  NaN

[98 rows x 2 columns]>

## Chi2 d'indépendance : compétences en fonction du parcours de stage. 

### Pour SN1 et Urgences

In [8]:
data_skill = pd.pivot_table(data=data, values="record_id", columns="order_1", index="skill", aggfunc="count")
display(data_skill.head)

<bound method NDFrame.head of order_1  SN1 avant Urgences  Urgences avant SN1
skill                                          
C1                       20                  21
C2                       10                  16
C3                       23                  23
C4                       33                  47
C5                       21                  24
C6                       13                   9>

In [9]:
chi_squared_result=chi2_contingency(data_skill)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  3.267149060289304 
La p-valeur du test est :  0.6588747770211364 
Nombre de degré de liberté :  5 

Le quantile de la loi du chi 2 à 5 degré de liberté associé au niveau de confiance 0.05 est 11.070497693516351 

Valeurs attendues : 
 [[18.92307692 22.07692308]
 [12.         14.        ]
 [21.23076923 24.76923077]
 [36.92307692 43.07692308]
 [20.76923077 24.23076923]
 [10.15384615 11.84615385]]


**Conclusion** : La p-value est supérieure à 0.05, on ne peut pas rejeter l'hypothèse nulle. On ne retrouve pas d'association entre le profil de compétences présentées et le parcours de stage. 

### Pour le stage ambulatoire

In [20]:
data_skill = pd.pivot_table(data=data, values="record_id", columns="ped_ambu", index="skill", aggfunc="count")
display(data_skill.head)

<bound method NDFrame.head of ped_ambu  non  oui
skill             
C1         33    8
C2         18    8
C3         39    7
C4         54   26
C5         32   13
C6         15    7>

In [21]:
chi_squared_result=chi2_contingency(data_skill)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  6.201520509209956 
La p-valeur du test est :  0.2871010892606544 
Nombre de degré de liberté :  5 

Le quantile de la loi du chi 2 à 5 degré de liberté associé au niveau de confiance 0.05 est 11.070497693516351 

Valeurs attendues : 
 [[30.11923077 10.88076923]
 [19.1         6.9       ]
 [33.79230769 12.20769231]
 [58.76923077 21.23076923]
 [33.05769231 11.94230769]
 [16.16153846  5.83846154]]


## Chi2 d'indépendance : spécialité en fonction du parcours de stage. 

### Pour SN1 et Urgences

In [23]:
data_specialty = pd.pivot_table(data=data, values="record_id", columns="order_1", index="specialty", aggfunc="count", fill_value=0)
display(data_specialty.head)

<bound method NDFrame.head of order_1                                SN1 avant Urgences  Urgences avant SN1
specialty                                                                    
Cardiologie                                             8                   7
Dermatologie                                            3                   9
Endocrinologie                                          7                   3
Ethique/Communication/Relation                         22                  22
Gastroentérologie                                       2                   3
Gynécologie                                             3                   7
Hématologie                                             1                   1
Infectiologie                                           4                   2
Médecine Interne - Immuno                               2                   2
Neurologie                                              1                   7
ORL                               

In [24]:
chi_squared_result=chi2_contingency(data_specialty)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  18.91974602159704 
La p-valeur du test est :  0.3967811053762454 
Nombre de degré de liberté :  18 

Le quantile de la loi du chi 2 à 18 degré de liberté associé au niveau de confiance 0.05 est 28.869299430392623 

Valeurs attendues : 
 [[ 6.89189189  8.10810811]
 [ 5.51351351  6.48648649]
 [ 4.59459459  5.40540541]
 [20.21621622 23.78378378]
 [ 2.2972973   2.7027027 ]
 [ 4.59459459  5.40540541]
 [ 0.91891892  1.08108108]
 [ 2.75675676  3.24324324]
 [ 1.83783784  2.16216216]
 [ 3.67567568  4.32432432]
 [ 5.51351351  6.48648649]
 [ 0.45945946  0.54054054]
 [ 4.13513514  4.86486486]
 [ 6.89189189  8.10810811]
 [12.40540541 14.59459459]
 [ 8.27027027  9.72972973]
 [ 4.13513514  4.86486486]
 [21.13513514 24.86486486]
 [ 2.75675676  3.24324324]]


### Pour le stage ambulatoire

In [26]:
data_specialty = pd.pivot_table(data=data, values="record_id", columns="ped_ambu", index="specialty", aggfunc="count", fill_value=0)
display(data_specialty.head)

<bound method NDFrame.head of ped_ambu                               non  oui
specialty                                      
Cardiologie                             10    5
Dermatologie                            11    1
Endocrinologie                           9    1
Ethique/Communication/Relation          34   10
Gastroentérologie                        1    4
Gynécologie                              8    2
Hématologie                              1    1
Infectiologie                            5    1
Médecine Interne - Immuno                3    1
Neurologie                               7    1
ORL                                      9    3
Ophtalmologie                            0    1
Orthopédie                               7    2
Pneumologie                              7    8
Psychiatrie                             21    6
Pédiatrie                               12    6
Rhumatologie                             7    2
Santé publique (Administratif/Social)   35   11
Urologie  

In [27]:
chi_squared_result=chi2_contingency(data_specialty)
alpha = 0.05

print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

La statistique de Pearson du test khi-deux est :  22.968592371641588 
La p-valeur du test est :  0.19179994232921752 
Nombre de degré de liberté :  18 

Le quantile de la loi du chi 2 à 18 degré de liberté associé au niveau de confiance 0.05 est 28.869299430392623 

Valeurs attendues : 
 [[11.06177606  3.93822394]
 [ 8.84942085  3.15057915]
 [ 7.37451737  2.62548263]
 [32.44787645 11.55212355]
 [ 3.68725869  1.31274131]
 [ 7.37451737  2.62548263]
 [ 1.47490347  0.52509653]
 [ 4.42471042  1.57528958]
 [ 2.94980695  1.05019305]
 [ 5.8996139   2.1003861 ]
 [ 8.84942085  3.15057915]
 [ 0.73745174  0.26254826]
 [ 6.63706564  2.36293436]
 [11.06177606  3.93822394]
 [19.91119691  7.08880309]
 [13.27413127  4.72586873]
 [ 6.63706564  2.36293436]
 [33.92277992 12.07722008]
 [ 4.42471042  1.57528958]]
