In [426]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from fanalysis.ca import CA
from matplotlib.ticker import PercentFormatter

from scipy.stats import chi2_contingency  
from scipy.stats import chi2
from scipy.stats import fisher_exact
from scipy.stats import MonteCarloMethod

data = pd.read_csv('data.csv')

In [427]:
# On ne garde que les 3 premiers caractères de la colonne tag pour comparer les SN1 et les SN2 indépendamment de la réalisation de stages supplémentaires ou non.
data['tag'] = data['tag'].str[:3]

## Comparaison de la distribution des familles de situation

In [428]:
data_FS = pd.pivot_table(data=data, values="record_id", columns="tag", index="FS", aggfunc="count")
data_FS

tag,SN1,SN2
FS,,
FS01,140,45
FS02,142,52
FS03,56,21
FS04,81,23
FS05,35,17
FS06,10,8
FS07,21,7
FS08,32,39
FS09,53,26


In [429]:
chi_squared_result=chi2_contingency(data_FS)
alpha = 0.05

print("\033[1;32mTest du Chi2 :\033[0m")
print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

Test du Chi2 :
La statistique de Pearson du test khi-deux est :  34.56532542960949 
La p-valeur du test est :  0.00014808141465778003 
Nombre de degré de liberté :  10 

Le quantile de la loi du chi 2 à 10 degré de liberté associé au niveau de confiance 0.05 est 18.307038053275146 

Valeurs attendues : 
 [[129.11458333  55.88541667]
 [135.39583333  58.60416667]
 [ 53.73958333  23.26041667]
 [ 72.58333333  31.41666667]
 [ 36.29166667  15.70833333]
 [ 12.5625       5.4375    ]
 [ 19.54166667   8.45833333]
 [ 49.55208333  21.44791667]
 [ 55.13541667  23.86458333]
 [ 24.42708333  10.57291667]
 [ 14.65625      6.34375   ]]


In [430]:
col_names = list(data_FS.columns)[0:]
row_names = list(data_FS.index)

X = data_FS[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des familles de situation en SN1 et SN2")
display(df)

Distribution des familles de situation en SN1 et SN2


,SN1,SN2
FS01,0.2322,0.1724
FS02,0.2355,0.1992
FS03,0.0929,0.0805
FS04,0.1343,0.0881
FS05,0.0580,0.0651
FS06,0.0166,0.0307
FS07,0.0348,0.0268
FS08,0.0531,0.1494
FS09,0.0879,0.0996
FS10,0.0365,0.0498


**Conclusion** : la distribution des familles de situation est significativement différente entre SN1 et SN2 (en analyse univariée).  
En SN1, les 4 FS les plus représentées sont les FS02, 01, 04 et 03. En SN2, on retrouve d'abord les FS02, 01, 08 et 04.  
D'une façon générale, les familles de situation les 4 premières familles de situation, qu'on observe plus fréquemment dans le RAQ (autre thèse) tout niveau de stage confondus semblent moins proposées en SN2 par rapport au SN1. Peut-être par soucis de valoriser des FS qui manqueraient pour certifier ? 

## Comparaison de la distribution des problématiques exemplaires

In [431]:
data_PE = pd.pivot_table(data=data, values="record_id", columns="tag", index="PE", aggfunc="count")
data_PE

tag,SN1,SN2
PE,,
PE01,144,40
PE02,74,36
PE03,26,13
PE04,58,23
PE05,56,33
PE06,41,25
PE07,35,12
PE08,73,23
PE09,52,23


In [432]:
chi_squared_result=chi2_contingency(data_PE)
alpha = 0.05

print("\033[1;32mTest du Chi2 :\033[0m")
print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

Test du Chi2 :
La statistique de Pearson du test khi-deux est :  18.849432352580475 
La p-valeur du test est :  0.026504013898568293 
Nombre de degré de liberté :  9 

Le quantile de la loi du chi 2 à 9 degré de liberté associé au niveau de confiance 0.05 est 16.918977604620444 

Valeurs attendues : 
 [[128.41666667  55.58333333]
 [ 76.77083333  33.22916667]
 [ 27.21875     11.78125   ]
 [ 56.53125     24.46875   ]
 [ 62.11458333  26.88541667]
 [ 46.0625      19.9375    ]
 [ 32.80208333  14.19791667]
 [ 67.          29.        ]
 [ 52.34375     22.65625   ]
 [ 53.73958333  23.26041667]]


In [433]:
col_names = list(data_PE.columns)[0:]
row_names = list(data_PE.index)

X = data_PE[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des problématiques exemplaires en SN1 et SN2")
display(df)

Distribution des problématiques exemplaires en SN1 et SN2


,SN1,SN2
PE01,0.2388,0.1533
PE02,0.1227,0.1379
PE03,0.0431,0.0498
PE04,0.0962,0.0881
PE05,0.0929,0.1264
PE06,0.0680,0.0958
PE07,0.0580,0.0460
PE08,0.1211,0.0881
PE09,0.0862,0.0881
PE10,0.0730,0.1264


Différence significative avec des variations surtout notables pour les PE01, 05, 10 et 08. 

## Comparaison de la distribution des compétences

In [434]:
data_skill = pd.pivot_table(data=data, values="record_id", columns="tag", index="skill", aggfunc="count")
data_skill

tag,SN1,SN2
skill,,
C1,120,41
C2,90,26
C3,137,46
C4,169,80
C5,63,45
C6,21,22


In [435]:
chi_squared_result=chi2_contingency(data_skill)
alpha = 0.05

print("\033[1;32mTest du Chi2 :\033[0m")
print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

Test du Chi2 :
La statistique de Pearson du test khi-deux est :  23.398836905432265 
La p-valeur du test est :  0.0002831599747125322 
Nombre de degré de liberté :  5 

Le quantile de la loi du chi 2 à 5 degré de liberté associé au niveau de confiance 0.05 est 11.070497693516351 

Valeurs attendues : 
 [[112.3255814   48.6744186 ]
 [ 80.93023256  35.06976744]
 [127.6744186   55.3255814 ]
 [173.72093023  75.27906977]
 [ 75.34883721  32.65116279]
 [ 30.          13.        ]]


In [436]:
col_names = list(data_skill.columns)[0:]
row_names = list(data_skill.index)

X = data_skill[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des compétences en SN1 et SN2")
display(df)

Distribution des compétences en SN1 et SN2


,SN1,SN2
C1,0.2000,0.1577
C2,0.1500,0.1000
C3,0.2283,0.1769
C4,0.2817,0.3077
C5,0.1050,0.1731
C6,0.0350,0.0846


## Comparaison de la distribution des items

In [437]:
data_item = pd.pivot_table(data=data, values="record_id", columns="tag", index="ecn_item", aggfunc="count", fill_value=0)
data_item

tag,SN1,SN2
ecn_item,,
Item 1,122,39
Item 100,2,0
Item 103,0,3
Item 105,1,1
Item 107,3,0
...,...,...
Item 94,1,4
Item 95,3,1
Item 96,3,1


In [438]:
chi_squared_result=chi2_contingency(data_item)
alpha = 0.05

print("\033[1;32mTest du Chi2 :\033[0m")
print("La statistique de Pearson du test khi-deux est : ", chi_squared_result[0], "\n"
      "La p-valeur du test est : ", chi_squared_result[1], "\n"
      "Nombre de degré de liberté : ", chi_squared_result[2], "\n")
print("Le quantile de la loi du chi 2 à", chi_squared_result[2], "degré de liberté associé au niveau de confiance",alpha,"est",chi2.ppf(1-alpha, chi_squared_result[2]) , "\n")

print("Valeurs attendues : \n", chi_squared_result[3])

Test du Chi2 :
La statistique de Pearson du test khi-deux est :  211.87324315938955 
La p-valeur du test est :  0.002732327506601803 
Nombre de degré de liberté :  158 

Le quantile de la loi du chi 2 à 158 degré de liberté associé au niveau de confiance 0.05 est 188.33169207932903 

Valeurs attendues : 
 [[112.60584795  48.39415205]
 [  1.39883041   0.60116959]
 [  2.09824561   0.90175439]
 [  1.39883041   0.60116959]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  6.99415205   3.00584795]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  2.79766082   1.20233918]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  2.09824561   0.90175439]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [  0.6994152    0.3005848 ]
 [ 10.49122807   4.50877193]
 [  4.89590643   2.10409357]
 [ 12.58947368   5.41052632]
 [  2.09824561   0.90175439]
 [  2.09824561   0.9017543

**Conclusion** : le Chi2 est significatif mais le tableau de contingence comporte de nombreuses valeurs nulles ou inférieures à 5. Il n'est donc théoriquement pas possible d'interpréter les résultats du Chi2.  
Pour essayer de lever cette limite, les valeurs inférieurs à 5 vont être rangés dans une catégorie "autre".

In [439]:
# Ajout d'une colonne "total" pour calculer les effectifs ligne par ligne
data_item['total'] = data_item['SN1'] + data_item['SN2']
data_item.reset_index(inplace=True)

# Seuil pour regrouper les lignes faibles (ex. : < 5)
seuil = 5

# Création d'un groupe : on garde le nom de l'item ou on remplace par "Autres"
data_item['groupe'] = data_item.apply(
    lambda row: row['ecn_item'] if row['SN1'] >= seuil and row['SN2'] >= seuil else 'Autres',
    axis=1
)

# Regroupement par groupe et somme des effectifs
df_grouped = data_item.groupby('groupe')[['SN1', 'SN2']].sum().reset_index()

print("\033[1;32mTest du Chi2 :\033[0m")
print(df_grouped)

# Tableau de contingence
contingency = df_grouped[['SN1', 'SN2']].values

df_prop = df_grouped.set_index('groupe')

# Test du Chi²
chi2, p, dof, expected = chi2_contingency(contingency)

# Affichage des résultats
print(f"Chi² = {chi2:.2f}")
print(f"p-value = {p:.4f}")
print(f"Degrés de liberté = {dof}")
print("\nTableau des fréquences attendues :\n", pd.DataFrame(expected, columns=['SN1', 'SN2'], index=df_grouped['groupe']))

Test du Chi2 :
tag    groupe  SN1  SN2
0      Autres  334  149
1      Item 1  122   39
2     Item 13   13    5
3    Item 146   46    9
4     Item 19    7   12
5    Item 204    7    7
6    Item 224   21    6
7    Item 247   10    7
8    Item 290   14    5
9    Item 361    6    6
10    Item 66   10    5
11    Item 74    8    7
Chi² = 26.48
p-value = 0.0055
Degrés de liberté = 11

Tableau des fréquences attendues :
                  SN1         SN2
groupe                          
Autres    337.817544  145.182456
Item 1    112.605848   48.394152
Item 13    12.589474    5.410526
Item 146   38.467836   16.532164
Item 19    13.288889    5.711111
Item 204    9.791813    4.208187
Item 224   18.884211    8.115789
Item 247   11.890058    5.109942
Item 290   13.288889    5.711111
Item 361    8.392982    3.607018
Item 66    10.491228    4.508772
Item 74    10.491228    4.508772


In [440]:
col_names = list(df_prop.columns)[0:]
row_names = list(df_prop.index)

X = df_prop[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des items en SN1 et SN2")
display(df)

Distribution des items en SN1 et SN2


,SN1,SN2
Autres,0.5585,0.5798
Item 1,0.2040,0.1518
Item 13,0.0217,0.0195
Item 146,0.0769,0.0350
Item 19,0.0117,0.0467
Item 204,0.0117,0.0272
Item 224,0.0351,0.0233
Item 247,0.0167,0.0272
Item 290,0.0234,0.0195
Item 361,0.0100,0.0233


**Conclusion:** Après création de la catégorie "Autres" le chi2 reste significatif. La distribution des Item entre SN1 et SN2 est donc bien significativement différente. Le tableau ci-dessus décrit les proportions des différents items. 

## Comparaison de la distribution des RC

In [441]:
data_RC = pd.pivot_table(data=data, values="record_id", columns="tag", index="RC", aggfunc="count", fill_value=0)
data_RC

tag,SN1,SN2
RC,,
?,0,1
ABCÈS SUPERFICIEL,1,0
ABDOMEN DOULOUREUX,2,0
ACCIDENT VASCULAIRE CÉRÉBRAL,0,1
ACNÉ VULGAIRE,1,2
...,...,...
ÉPIGASTRALGIE,1,0
ÉPILEPSIE,1,0
ÉPISTAXIS,0,1


Devant le nombre de valeurs inférieurs à 5 et même égales à 0, création de la catégorie "Autres" d'emblée : 

In [442]:
# Ajout d'une colonne "total" pour calculer les effectifs ligne par ligne
data_RC['total'] = data_RC['SN1'] + data_RC['SN2']
data_RC.reset_index(inplace=True)

# Seuil pour regrouper les lignes faibles (ex. : < 5)
seuil = 5

# Création d'un groupe : on garde le nom de l'item ou on remplace par "Autres"
data_RC['groupe'] = data_RC.apply(
    lambda row: row['RC'] if row['SN1'] >= seuil and row['SN2'] >= seuil else 'Autres',
    axis=1
)

# Regroupement par groupe et somme des effectifs
df_grouped = data_RC.groupby('groupe')[['SN1', 'SN2']].sum().reset_index()

print("\033[1;32mTest du Chi2, avec création d'une catégorie \"Autres\" :\033[0m")
print("La catégorie \"Autres\" regroupe tous les RC avec une modalité strictement inférieure à 5. \n")
print(df_grouped)

# Tableau de contingence
contingency = df_grouped[['SN1', 'SN2']].values

df_prop = df_grouped.set_index('groupe')

# Test du Chi²
chi2, p, dof, expected = chi2_contingency(contingency)

# Affichage des résultats
print(f"Chi² = {chi2:.2f}")
print(f"p-value = {p:.4f}")
print(f"Degrés de liberté = {dof}")
print("\nTableau des fréquences attendues :\n", pd.DataFrame(expected, columns=['SN1', 'SN2'], index=df_grouped['groupe']))

Test du Chi2, avec création d'une catégorie "Autres" :
La catégorie "Autres" regroupe tous les RC avec une modalité strictement inférieure à 5. 

tag                    groupe  SN1  SN2
0                      Autres  249  108
1           DIABÈTE DE TYPE 2   11    7
2                DYSLIPIDÉMIE   14    5
3     DÉPISTAGE ET PRÉVENTION   50   11
4                  DÉPRESSION   11   13
5                         HTA   22    6
6    PROCÉDURE ADMINISTRATIVE   60   47
7                        TOUX    7    7
8                 VACCINATION   48   12
Chi² = 26.71
p-value = 0.0008
Degrés de liberté = 8

Tableau des fréquences attendues :
                                  SN1         SN2
groupe                                          
Autres                    244.918605  112.081395
DIABÈTE DE TYPE 2          12.348837    5.651163
DYSLIPIDÉMIE               13.034884    5.965116
DÉPISTAGE ET PRÉVENTION    41.848837   19.151163
DÉPRESSION                 16.465116    7.534884
HTA                   

In [443]:
col_names = list(df_prop.columns)[0:]
row_names = list(df_prop.index)

X = df_prop[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des compétences en SN1 et SN2")
display(df)

Distribution des compétences en SN1 et SN2


,SN1,SN2
Autres,0.5275,0.5000
DIABÈTE DE TYPE 2,0.0233,0.0324
DYSLIPIDÉMIE,0.0297,0.0231
DÉPISTAGE ET PRÉVENTION,0.1059,0.0509
DÉPRESSION,0.0233,0.0602
HTA,0.0466,0.0278
PROCÉDURE ADMINISTRATIVE,0.1271,0.2176
TOUX,0.0148,0.0324
VACCINATION,0.1017,0.0556


## Comparaison des spécialités 

In [444]:
data_specialty = pd.pivot_table(data=data, values="record_id", columns="tag", index="specialty", aggfunc="count", fill_value=0)
display(data_specialty)

tag,SN1,SN2
specialty,,
Cardiologie,55,15
Dermatologie,25,12
Endocrinologie,28,10
Ethique/Communication/Relation,124,44
Gastroentérologie,21,5
Gynécologie,31,10
Hématologie,2,2
Infectiologie,22,6
Médecine Interne - Immuno,2,4


In [445]:
# Test du Chi²
chi2, p, dof, expected = chi2_contingency(data_specialty)

# Affichage des résultats
print("\033[1;32mTest du Chi2 :\033[0m")
print(f"Chi² = {chi2:.2f}")
print(f"p-value = {p:.4f}")
print(f"Degrés de liberté = {dof}")
print("\nTableau des fréquences attendues :\n", pd.DataFrame(expected, columns=['SN1', 'SN2'], index=data_specialty.index))

Test du Chi2 :
Chi² = 34.84
p-value = 0.0146
Degrés de liberté = 19

Tableau des fréquences attendues :
                                               SN1        SN2
specialty                                                   
Cardiologie                             48.918605  21.081395
Dermatologie                            25.856977  11.143023
Endocrinologie                          26.555814  11.444186
Ethique/Communication/Relation         117.404651  50.595349
Gastroentérologie                       18.169767   7.830233
Gynécologie                             28.652326  12.347674
Hématologie                              2.795349   1.204651
Infectiologie                           19.567442   8.432558
Médecine Interne - Immuno                4.193023   1.806977
Neurologie                              18.868605   8.131395
Néphrologie                              2.795349   1.204651
ORL                                     22.362791   9.637209
Ophtalmologie                            

In [446]:
col_names = list(data_specialty.columns)[0:]
row_names = list(data_specialty.index)

X = data_specialty[col_names].values

col_sum = np.sum(X, axis=0)
col_profile = (X / col_sum[np.newaxis, :]).round(4)

df = pd.DataFrame(col_profile, index=row_names, columns=col_names)
print("Distribution des compétences en SN1 et SN2")
display(df)

Distribution des compétences en SN1 et SN2


,SN1,SN2
Cardiologie,0.0915,0.0579
Dermatologie,0.0416,0.0463
Endocrinologie,0.0466,0.0386
Ethique/Communication/Relation,0.2063,0.1699
Gastroentérologie,0.0349,0.0193
Gynécologie,0.0516,0.0386
Hématologie,0.0033,0.0077
Infectiologie,0.0366,0.0232
Médecine Interne - Immuno,0.0033,0.0154
Neurologie,0.0316,0.0309


## Comparaison des distributions pour les 10 premiers items

In [447]:
top10_items = ['Item 1', 'Item 13', 'Item 146', 'Item 19', 'Item 204', 'Item 224', 'Item 247', 'Item 290', 'Item 361', 'Item 66']

### Item et problématiques exemplaire

In [448]:
# Pour les problématiques exemplaires 

rng = np.random.default_rng()
method = MonteCarloMethod()

for item in top10_items:
    print(f"\033[1;32mTest exact de Fisher avec méthode de Monte Carlo ({item}):\033[0m")
    sample = data.loc[data['ecn_item'] == item]
    sample = pd.pivot_table(data=sample, values="record_id", columns="tag", index="PE", aggfunc="count", fill_value=0)
    contingency = sample[['SN1', 'SN2']].values
    print(contingency)
    odds_ratio, p_value = fisher_exact(contingency, method=method)
    print(f"\nTableau de contingence pour {item} :")
    print(f"p-value : {p_value}")
    display(sample)



Test exact de Fisher avec méthode de Monte Carlo (Item 1):
[[ 7  2]
 [ 0  1]
 [41 17]
 [ 2  0]
 [ 4  2]
 [ 2  0]
 [60 14]
 [ 6  3]]

Tableau de contingence pour Item 1 :
p-value : 0.4486


tag,SN1,SN2
PE,,
PE01,7,2
PE03,0,1
PE04,41,17
PE05,2,0
PE06,4,2
PE07,2,0
PE08,60,14
PE10,6,3


Test exact de Fisher avec méthode de Monte Carlo (Item 13):
[[ 1  0]
 [ 0  1]
 [11  2]
 [ 1  0]
 [ 0  1]
 [ 0  1]]

Tableau de contingence pour Item 13 :
p-value : 0.0975


tag,SN1,SN2
PE,,
PE01,1,0
PE04,0,1
PE05,11,2
PE08,1,0
PE09,0,1
PE10,0,1


Test exact de Fisher avec méthode de Monte Carlo (Item 146):
[[12  1]
 [ 6  2]
 [ 2  0]
 [ 2  1]
 [ 0  1]
 [ 1  0]
 [14  2]
 [ 5  1]
 [ 4  1]]

Tableau de contingence pour Item 146 :
p-value : 0.4722


tag,SN1,SN2
PE,,
PE01,12,1
PE02,6,2
PE03,2,0
PE04,2,1
PE05,0,1
PE06,1,0
PE07,14,2
PE09,5,1
PE10,4,1


Test exact de Fisher avec méthode de Monte Carlo (Item 19):
[[ 0  1]
 [ 7 10]
 [ 0  1]]

Tableau de contingence pour Item 19 :
p-value : 1.0


tag,SN1,SN2
PE,,
PE01,0,1
PE05,7,10
PE10,0,1


Test exact de Fisher avec méthode de Monte Carlo (Item 204):
[[0 1]
 [1 4]
 [2 0]
 [1 1]
 [3 1]]

Tableau de contingence pour Item 204 :
p-value : 0.2567


tag,SN1,SN2
PE,,
PE01,0,1
PE02,1,4
PE03,2,0
PE06,1,1
PE09,3,1


Test exact de Fisher avec méthode de Monte Carlo (Item 224):
[[4 0]
 [6 1]
 [3 2]
 [1 1]
 [2 0]
 [2 1]
 [2 0]
 [1 1]]

Tableau de contingence pour Item 224 :
p-value : 0.6462


tag,SN1,SN2
PE,,
PE01,4,0
PE02,6,1
PE03,3,2
PE06,1,1
PE07,2,0
PE08,2,1
PE09,2,0
PE10,1,1


Test exact de Fisher avec méthode de Monte Carlo (Item 247):
[[5 2]
 [3 2]
 [1 1]
 [0 2]
 [1 0]]

Tableau de contingence pour Item 247 :
p-value : 0.556


tag,SN1,SN2
PE,,
PE01,5,2
PE02,3,2
PE07,1,1
PE09,0,2
PE10,1,0


Test exact de Fisher avec méthode de Monte Carlo (Item 290):
[[7 1]
 [1 0]
 [2 1]
 [4 1]
 [0 2]]

Tableau de contingence pour Item 290 :
p-value : 0.1347


tag,SN1,SN2
PE,,
PE01,7,1
PE03,1,0
PE07,2,1
PE09,4,1
PE10,0,2


Test exact de Fisher avec méthode de Monte Carlo (Item 361):
[[3 2]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]]

Tableau de contingence pour Item 361 :
p-value : 1.0


tag,SN1,SN2
PE,,
PE01,3,2
PE02,0,1
PE06,1,1
PE07,0,1
PE08,1,0
PE10,1,1


Test exact de Fisher avec méthode de Monte Carlo (Item 66):
[[3 0]
 [1 2]
 [2 0]
 [1 0]
 [0 1]
 [0 2]
 [3 0]]

Tableau de contingence pour Item 66 :
p-value : 0.0517


tag,SN1,SN2
PE,,
PE01,3,0
PE02,1,2
PE04,2,0
PE05,1,0
PE08,0,1
PE09,0,2
PE10,3,0


### Item et étape du raisonnement

In [449]:
for item in top10_items:
    sample = data.loc[data['ecn_item'] == item]
    sample = sample.groupby(['tag']).agg(
        diagnostic = ('step_diag', 'sum'),
        prescription = ('step_PEC_TTT', 'sum'), 
        autre = ('step_autre', 'sum')
    )

    sample = sample.T

    contingency = sample[['SN1', 'SN2']].values
    print(f"\nTableau de contingence pour {item} :")
    display(sample)
    try:
        odds_ratio, p_value = fisher_exact(contingency, method=method)
        print(f"\033[1;32mTest exact de Fisher avec méthode de Monte Carlo ({item}):\033[0m")
        print(f"p-value : {p_value}")
    except Exception as e: 
        print(f"[ERREUR] : {e}")
    


Tableau de contingence pour Item 1 :


tag,SN1,SN2
diagnostic,0,0
prescription,0,0
autre,122,39


[ERREUR] : `x` must contain only non-negative values

Tableau de contingence pour Item 13 :


tag,SN1,SN2
diagnostic,0,0
prescription,0,0
autre,13,5


[ERREUR] : `x` must contain only non-negative values

Tableau de contingence pour Item 146 :


tag,SN1,SN2
diagnostic,0,0
prescription,46,9
autre,0,0


Test exact de Fisher avec méthode de Monte Carlo (Item 146):
p-value : 1.0

Tableau de contingence pour Item 19 :


tag,SN1,SN2
diagnostic,0,0
prescription,0,0
autre,7,12


[ERREUR] : `x` must contain only non-negative values

Tableau de contingence pour Item 204 :


tag,SN1,SN2
diagnostic,2,2
prescription,6,6
autre,0,0


Test exact de Fisher avec méthode de Monte Carlo (Item 204):
p-value : 1.0

Tableau de contingence pour Item 224 :


tag,SN1,SN2
diagnostic,7,1
prescription,14,5
autre,0,0


Test exact de Fisher avec méthode de Monte Carlo (Item 224):
p-value : 0.6334

Tableau de contingence pour Item 247 :


tag,SN1,SN2
diagnostic,2,2
prescription,8,5
autre,0,0


Test exact de Fisher avec méthode de Monte Carlo (Item 247):
p-value : 1.0

Tableau de contingence pour Item 290 :


tag,SN1,SN2
diagnostic,13,5
prescription,0,0
autre,1,0


Test exact de Fisher avec méthode de Monte Carlo (Item 290):
p-value : 1.0

Tableau de contingence pour Item 361 :


tag,SN1,SN2
diagnostic,2,1
prescription,5,6
autre,0,0


Test exact de Fisher avec méthode de Monte Carlo (Item 361):
p-value : 1.0

Tableau de contingence pour Item 66 :


tag,SN1,SN2
diagnostic,4,1
prescription,7,3
autre,0,1


Test exact de Fisher avec méthode de Monte Carlo (Item 66):
p-value : 0.4896


## Distribution des items en fonction des spécialités

In [450]:
specialties = data['specialty'].unique()
specialties = specialties[~pd.isna(specialties)]
print(specialties)

for specialty in specialties:
    data_spe = data.loc[data['specialty'] == specialty]
    data_spe = pd.pivot_table(data=data_spe, values="record_id", columns="tag", index="ecn_item", aggfunc="count", fill_value=0)
    try: 
        print(f"\n{specialty}")
        display(data_spe)
        contingency = data_spe[['SN1', 'SN2']].values
        odds_ratio, p_value = fisher_exact(contingency, method=method)
        print(f"\033[1;32mTest exact de Fisher avec méthode de Monte Carlo ({specialty}) :\033[0m")
        print(f"p-value : {p_value}")
    except Exception as e:
        print(f"[ERREUR] : {e}")

['Endocrinologie' 'Psychiatrie' 'Ethique/Communication/Relation'
 'Pneumologie' 'Médecine Interne - Immuno' 'Dermatologie' 'Gynécologie'
 'Santé publique (Administratif/Social)' 'Pédiatrie' 'Cardiologie'
 'Orthopédie' 'Rhumatologie' 'Gastroentérologie' 'Infectiologie'
 'Neurologie' 'Urologie' 'Ophtalmologie' 'ORL' 'Néphrologie' 'Hématologie']

Endocrinologie


tag,SN1,SN2
ecn_item,,
Item 1,1,0
Item 128,1,0
Item 219,0,1
Item 241,1,0
Item 242,2,0
Item 243,4,2
Item 246,2,0
Item 247,10,7
Item 249,1,0


Test exact de Fisher avec méthode de Monte Carlo (Endocrinologie) :
p-value : 0.8911

Psychiatrie


tag,SN1,SN2
ecn_item,,
Item 1,2,0
Item 110,6,2
Item 126,0,1
Item 144,0,1
Item 182,1,2
Item 249,1,0
Item 352,0,1
Item 353,2,2
Item 66,10,4


Test exact de Fisher avec méthode de Monte Carlo (Psychiatrie) :
p-value : 0.2598

Ethique/Communication/Relation


tag,SN1,SN2
ecn_item,,
Item 1,118,39
Item 16,1,0
Item 2,0,1
Item 3,0,2
Item 324,0,1
Item 59,1,0
Item 6,1,0
Item 7,1,1
Item 9,2,0


Test exact de Fisher avec méthode de Monte Carlo (Ethique/Communication/Relation) :
p-value : 0.0717

Pneumologie


tag,SN1,SN2
ecn_item,,
Item 154,2,1
Item 159,5,2
Item 166,0,1
Item 188,2,3
Item 204,7,7
Item 269,1,0
Item 290,1,1
Item 75,12,0


Test exact de Fisher avec méthode de Monte Carlo (Pneumologie) :
p-value : 0.0195

Médecine Interne - Immuno


tag,SN1,SN2
ecn_item,,
Item 134,0,2
Item 135,1,0
Item 186,0,1
Item 248,0,1
Item 251,1,0


Test exact de Fisher avec méthode de Monte Carlo (Médecine Interne - Immuno) :
p-value : [0.4615]

Dermatologie


tag,SN1,SN2
ecn_item,,
Item 111,1,2
Item 113,0,1
Item 116,1,0
Item 155,7,1
Item 168,1,1
Item 171,2,1
Item 173,3,0
Item 187,6,2
Item 239,0,1


Test exact de Fisher avec méthode de Monte Carlo (Dermatologie) :
p-value : 0.3086

Gynécologie


tag,SN1,SN2
ecn_item,,
Item 124,2,1
Item 135,1,0
Item 146,2,0
Item 155,1,2
Item 162,2,1
Item 166,0,1
Item 23,2,2
Item 24,2,0
Item 290,5,1


Test exact de Fisher avec méthode de Monte Carlo (Gynécologie) :
p-value : 0.4663

Santé publique (Administratif/Social)


tag,SN1,SN2
ecn_item,,
Item 105,0,1
Item 11,0,1
Item 119,2,1
Item 12,1,0
Item 13,12,5
Item 133,2,1
Item 139,1,2
Item 16,2,5
Item 17,0,3


Test exact de Fisher avec méthode de Monte Carlo (Santé publique (Administratif/Social)) :
p-value : 0.0489

Pédiatrie


tag,SN1,SN2
ecn_item,,
Item 1,1,0
Item 146,34,7
Item 147,1,0
Item 150,1,0
Item 164,2,3
Item 168,0,1
Item 176,1,0
Item 253,2,0
Item 271,3,0


Test exact de Fisher avec méthode de Monte Carlo (Pédiatrie) :
p-value : 0.0553

Cardiologie


tag,SN1,SN2
ecn_item,,
Item 13,1,0
Item 213,1,0
Item 222,6,2
Item 223,12,3
Item 224,21,6
Item 226,3,1
Item 230,2,0
Item 232,0,1
Item 234,2,0


Test exact de Fisher avec méthode de Monte Carlo (Cardiologie) :
p-value : 0.8049

Orthopédie


tag,SN1,SN2
ecn_item,,
Item 120,1,0
Item 122,1,0
Item 177,0,1
Item 199,1,0
Item 230,1,0
Item 256,1,0
Item 267,0,1
Item 326,1,0
Item 361,4,5


Test exact de Fisher avec méthode de Monte Carlo (Orthopédie) :
p-value : [1.]

Rhumatologie


tag,SN1,SN2
ecn_item,,
Item 128,12,2
Item 129,5,2
Item 134,1,0
Item 135,2,0
Item 200,3,0
Item 270,7,4
Item 327,1,0
Item 361,2,1
Item 95,1,0


Test exact de Fisher avec méthode de Monte Carlo (Rhumatologie) :
p-value : 0.8383

Gastroentérologie


tag,SN1,SN2
ecn_item,,
Item 167,1,1
Item 172,1,0
Item 176,0,1
Item 219,2,0
Item 269,4,0
Item 271,1,1
Item 272,3,0
Item 274,1,0
Item 283,2,0


Test exact de Fisher avec méthode de Monte Carlo (Gastroentérologie) :
p-value : [0.2508]

Infectiologie


tag,SN1,SN2
ecn_item,,
Item 146,10,2
Item 147,1,0
Item 162,1,0
Item 169,2,0
Item 173,1,0
Item 174,0,1
Item 175,7,2
Item 185,0,1


Test exact de Fisher avec méthode de Monte Carlo (Infectiologie) :
p-value : 0.4166

Neurologie


tag,SN1,SN2
ecn_item,,
Item 100,2,0
Item 105,1,0
Item 107,3,0
Item 110,0,1
Item 118,1,0
Item 119,0,1
Item 132,1,2
Item 135,2,0
Item 334,1,0


Test exact de Fisher avec méthode de Monte Carlo (Neurologie) :
p-value : [0.5612]

Urologie


tag,SN1,SN2
ecn_item,,
Item 125,1,0
Item 127,0,1
Item 161,7,1
Item 162,1,0
Item 260,1,0
Item 265,0,1
Item 290,7,3


Test exact de Fisher avec méthode de Monte Carlo (Urologie) :
p-value : 0.3228

Ophtalmologie


tag,SN1,SN2
ecn_item,,
Item 168,0,1
Item 39,1,0
Item 83,1,0
Item 84,1,0


Test exact de Fisher avec méthode de Monte Carlo (Ophtalmologie) :
p-value : [1.]

ORL


tag,SN1,SN2
ecn_item,,
Item 103,0,3
Item 110,0,1
Item 148,2,1
Item 149,6,3
Item 150,6,2
Item 186,3,0
Item 188,0,1
Item 217,1,0
Item 324,1,0


Test exact de Fisher avec méthode de Monte Carlo (ORL) :
p-value : 0.1052

Néphrologie


tag,SN1
ecn_item,
Item 234,1
Item 259,1
Item 264,1
Item 267,1


[ERREUR] : "['SN2'] not in index"

Hématologie


tag,SN1,SN2
ecn_item,,
Item 212,1,0
Item 213,0,1
Item 319,0,1
Item 96,1,0


Test exact de Fisher avec méthode de Monte Carlo (Hématologie) :
p-value : [1.]
